/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package alumni_202457201066;

import alumni_202457201066.panelDashboard;
import com.formdev.flatlaf.FlatLightLaf;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;

/**
 *
 * @author Sukma Nur
 */
public class Dasboard extends javax.swing.JFrame {

    /**
     * Creates new form Dasboard
     */
    public Dasboard() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MainPanel = new javax.swing.JPanel();
        sidebar = new javax.swing.JPanel();
        bDashboard = new javax.swing.JButton();
        bJurusan = new javax.swing.JButton();
        bGuru = new javax.swing.JButton();
        bKelas = new javax.swing.JButton();
        bSiswa = new javax.swing.JButton();
        bAbout = new javax.swing.JButton();
        bLogout = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        conten = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        sidebar.setBackground(new java.awt.Color(102, 153, 255));

        bDashboard.setBackground(new java.awt.Color(102, 153, 255));
        bDashboard.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        bDashboard.setForeground(new java.awt.Color(255, 255, 255));
        bDashboard.setIcon(new javax.swing.ImageIcon(getClass().getResource("/alumni_202457201066/gambar/icons8-dashboard-20.png"))); // NOI18N
        bDashboard.setText("Dashboard");
        bDashboard.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
        bDashboard.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        bDashboard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bDashboardActionPerformed(evt);
            }
        });

        bJurusan.setBackground(new java.awt.Color(102, 153, 255));
        bJurusan.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        bJurusan.setForeground(new java.awt.Color(255, 255, 255));
        bJurusan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/alumni_202457201066/gambar/icons8-school-20.png"))); // NOI18N
        bJurusan.setText("Jurusan");
        bJurusan.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
        bJurusan.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        bJurusan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bJurusanActionPerformed(evt);
            }
        });

        bGuru.setBackground(new java.awt.Color(102, 153, 255));
        bGuru.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        bGuru.setForeground(new java.awt.Color(255, 255, 255));
        bGuru.setIcon(new javax.swing.ImageIcon(getClass().getResource("/alumni_202457201066/gambar/icons8-teacher-20.png"))); // NOI18N
        bGuru.setText("Guru");
        bGuru.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
        bGuru.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        bGuru.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bGuruActionPerformed(evt);
            }
        });

        bKelas.setBackground(new java.awt.Color(102, 153, 255));
        bKelas.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        bKelas.setForeground(new java.awt.Color(255, 255, 255));
        bKelas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/alumni_202457201066/gambar/icons8-class-20.png"))); // NOI18N
        bKelas.setText("Kelas");
        bKelas.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
        bKelas.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        bKelas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bKelasActionPerformed(evt);
            }
        });

        bSiswa.setBackground(new java.awt.Color(102, 153, 255));
        bSiswa.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        bSiswa.setForeground(new java.awt.Color(255, 255, 255));
        bSiswa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/alumni_202457201066/gambar/icons8-schoolboy-at-a-desk-20.png"))); // NOI18N
        bSiswa.setText("Siswa");
        bSiswa.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
        bSiswa.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        bSiswa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bSiswaActionPerformed(evt);
            }
        });

        bAbout.setBackground(new java.awt.Color(102, 153, 255));
        bAbout.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        bAbout.setForeground(new java.awt.Color(255, 255, 255));
        bAbout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/alumni_202457201066/gambar/icons8-about-20.png"))); // NOI18N
        bAbout.setText("About");
        bAbout.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
        bAbout.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        bAbout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bAboutActionPerformed(evt);
            }
        });

        bLogout.setBackground(new java.awt.Color(102, 153, 255));
        bLogout.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        bLogout.setForeground(new java.awt.Color(255, 255, 255));
        bLogout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/alumni_202457201066/gambar/icons8-logout-20.png"))); // NOI18N
        bLogout.setText("Logout");
        bLogout.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
        bLogout.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        bLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bLogoutActionPerformed(evt);
            }
        });

        jLabel1.setBackground(new java.awt.Color(102, 204, 255));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("ALOOMNI");

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/alumni_202457201066/gambar/icons8-student-24.png"))); // NOI18N

        javax.swing.GroupLayout sidebarLayout = new javax.swing.GroupLayout(sidebar);
        sidebar.setLayout(sidebarLayout);
        sidebarLayout.setHorizontalGroup(
            sidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sidebarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(sidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bDashboard, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bJurusan, javax.swing.GroupLayout.DEFAULT_SIZE, 186, Short.MAX_VALUE)
                    .addComponent(bGuru, javax.swing.GroupLayout.DEFAULT_SIZE, 186, Short.MAX_VALUE)
                    .addComponent(bKelas, javax.swing.GroupLayout.DEFAULT_SIZE, 186, Short.MAX_VALUE)
                    .addComponent(bSiswa, javax.swing.GroupLayout.DEFAULT_SIZE, 186, Short.MAX_VALUE)
                    .addComponent(bAbout, javax.swing.GroupLayout.DEFAULT_SIZE, 186, Short.MAX_VALUE)
                    .addComponent(bLogout, javax.swing.GroupLayout.DEFAULT_SIZE, 186, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(sidebarLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        sidebarLayout.setVerticalGroup(
            sidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sidebarLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(sidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addComponent(bDashboard)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bJurusan)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bGuru)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(bKelas)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(bSiswa)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(bAbout)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(bLogout)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        conten.setBackground(new java.awt.Color(255, 255, 255));
        conten.setLayout(new java.awt.CardLayout());

        javax.swing.GroupLayout MainPanelLayout = new javax.swing.GroupLayout(MainPanel);
        MainPanel.setLayout(MainPanelLayout);
        MainPanelLayout.setHorizontalGroup(
            MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MainPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(sidebar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(conten, javax.swing.GroupLayout.PREFERRED_SIZE, 1111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        MainPanelLayout.setVerticalGroup(
            MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(sidebar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(MainPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(conten, javax.swing.GroupLayout.DEFAULT_SIZE, 760, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 1267, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void bDashboardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bDashboardActionPerformed
        // TODO add your handling code here:
          conten.removeAll();
          conten.add(new panelDashboard());
          conten.repaint();
          conten.revalidate();
    }//GEN-LAST:event_bDashboardActionPerformed

    private void bSiswaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bSiswaActionPerformed
        // TODO add your handling code here:
          conten.removeAll();
          conten.add(new PanelSiswa());
          conten.repaint();
          conten.revalidate();
    }//GEN-LAST:event_bSiswaActionPerformed

    private void bLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bLogoutActionPerformed
        // TODO add your handling code here:
        String judul = "Konfirmasi";
        String pesan = "Apakah Anda yakin ingin keluar";
        int optionType = JOptionPane.YES_NO_OPTION;
        int messageType = JOptionPane.QUESTION_MESSAGE;
        
        int pilihan = JOptionPane.showConfirmDialog(
                this, pesan, judul, optionType, messageType);
        if (pilihan == JOptionPane.YES_OPTION){
            System.exit(0);
        } else if(pilihan == JOptionPane.NO_OPTION){
            System.out.println("User clicked No - Staying logged in.");
        } else if(pilihan == JOptionPane.CLOSED_OPTION){
            System.out.println("Dialog closed without selection.");
        }
    }//GEN-LAST:event_bLogoutActionPerformed

    private void bJurusanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bJurusanActionPerformed
        // TODO add your handling code here:
        conten.removeAll();
        conten.add(new PanelJurusan());
        conten.repaint();
        conten.revalidate();
    }//GEN-LAST:event_bJurusanActionPerformed

    private void bGuruActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bGuruActionPerformed
        // TODO add your handling code here:
        conten.removeAll();
        conten.add(new PanelGuru());
        conten.repaint();
        conten.revalidate();
    }//GEN-LAST:event_bGuruActionPerformed

    private void bKelasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bKelasActionPerformed
        // TODO add your handling code here:
        conten.removeAll();
        conten.add(new PanelKelas());
        conten.repaint();
        conten.revalidate();
    }//GEN-LAST:event_bKelasActionPerformed

    private void bAboutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bAboutActionPerformed
        // TODO add your handling code here:
        conten.removeAll();
        conten.add(new PanelAbout());
        conten.repaint();
        conten.revalidate(); 
    }//GEN-LAST:event_bAboutActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
         //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
      
            /* Set the Nimbus look and feel */
            //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
            /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
            * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
            */
            
              try {
            UIManager.setLookAndFeel(new FlatLightLaf());
        } catch (UnsupportedLookAndFeelException unsupportedLookAndFeelException) {
        }
          
            //</editor-fold>UIManager.setLookAndFeel(new FlatLightLaf());
            
            /* Create and display the form */
            
       
        //</editor-fold>
        

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Dasboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel MainPanel;
    private javax.swing.JButton bAbout;
    private javax.swing.JButton bDashboard;
    private javax.swing.JButton bGuru;
    private javax.swing.JButton bJurusan;
    private javax.swing.JButton bKelas;
    private javax.swing.JButton bLogout;
    private javax.swing.JButton bSiswa;
    private javax.swing.JPanel conten;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel sidebar;
    // End of variables declaration//GEN-END:variables
}
